### ISSUE TITLE
Optional translation

### ISSUE THREAD

**Issue by ghost** [rn0x/Pleroma_Bot#2]
Hello,

Google translate can be a hit or miss. Adding automated translation without the ability to moderate it first can cause some funny posts at best, and might cause offending posts at worst. 
Having the option to enable or disable it would be very nice and it will allow you to reach to border audience since not all people would want to use this for Arabic content. 

Thank you!

**Comment by rn0x** [comment]
الآن يمكنك تفعيل وتعطيل الترجمة عبر ملف config.json

**Comment by ghost** [comment]
أشكرك جزيل الشكر صديقي على المجهود
