### ISSUE TITLE
Auto cleanup

### ISSUE THREAD

**Issue by ghost** [rn0x/Pleroma_Bot#4]
Hello,

When using the bot for a while, the images folder gets seriously big. The sentRss.json also does grow.
Can you implement to automaticly flush the images directory and the json file?

Thank you!

**Comment by rn0x** [comment]
الآن اصبح يكتب على صورة واحدة ويرسل المخزن الوقت bufferr 
ايضا صار لكل feed ملف خاص يتم حفظ فيه آخر رابط

**Comment by ghost** [comment]
جميل جدا!
شكرا جزيلا لك صديقي على العمل السريع. سأقوم بتجربة البرنامج عن قريب وإن شاء الله يكون على خير ما يرام!
كل الشكر والتقدير لك على الوقت والجهد المبذول في البرنامج وشكرا لأنك تتعامل مع طلبات المستخدمين بكل سرعة و إحترافية
